config/routes.rb
Rails.application.routes.draw do
  resources :pins
  devise_for :users
  root "pages#home"
  get "about" => "pages#about"
  get "team" => "pages#team"

end

app/models/pin.rb
class Pin < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def team
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]

  def index
    @pins = Pin.all
  end

  def show
  end

  def new
    @pin = Pin.new
  end

  def edit
  end

  def create
    @pin = Pin.new(pin_params)
    
      if @pin.save
        redirect_to @pin, notice: 'Pin was successfully created.'

      else
        render :new
      end
  end

  def update
      if @pin.update(pin_params)
        redirect_to @pin, notice: 'Pin was successfully updated.'
      else
        render :edit 
      end
  end

  def destroy
    @pin.destroy
      redirect_to pins_url, notice: 'Pin was successfully destroyed.'
  end

  private

    def set_pin
      @pin = Pin.find(params[:id])
    end


    def pin_params
      params.require(:pin).permit(:description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-static-top navbar-default" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->

    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
        <%= link_to "Pinteresting", root_path, class: "navbar-brand" %>
      </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Search</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Team", team_path %></li>
          <% if user_signed_in? %>
          <li><%= link_to "Account", edit_user_registration_path %></li>
            <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "Sign In", new_user_session_path %></li>
          <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pinning</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

    		<meta name="viewport" content="width=device-width, initial-scale=1">
    		
</head>
<body>
		<%= render 'layouts/header' %>
		<div class="container">
      <% flash.each do |name, msg| %>
        <%= content_tag(:div, msg, class: "alert alert-info") %>

      <% end %>
			<%= yield %>
		</div>	

</body>
</html>

app/views/pages/about.html.erb
<h1>About Us</h1>
<p>We're crushing it like we do...</p>

app/views/pages/home.html.erb
<div class="jumbotron center">
	<h1>Welcome to My App</h1>
	<% if user_signed_in? %>
		Welcome To The Members Area Bitches!
		<% else %>

		<p> 
			<%= link_to "Log In", new_user_session_path , class: "btn btn-default btn-lg" %>
			<%= link_to "Sign Up", new_user_registration_path , class: "btn btn-primary btn-lg" %>
		</p>
<% end %>
		
</div>

app/views/pages/team.html.erb
<h1>Meet The Team</h1>
<p>Our team comes from a wide variety of industries, all with a passion for allowing users to engage with their images and videos.</p>
<p>In a short period of time we've gone from the 4 of us working as our user base to 10,000 users</p>
<div class="row">
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <img src="http://howimbuildingmylife.com/wp-content/uploads/2015/08/IMG_9060-e1440873787994.jpg" alt="TWH3">
      <div class="caption">
        <h3>Thomas Wilson Hanks III</h3>
        <p>TWH3 Comes to us via New Jersey, the city by the sea...is that what they call it? Who knows for sure? As the most junior member of our team, TWH3 is the life of any party as evidenced by his large number of selfies.</p>
      </div>
    </div>
  </div>

  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <img src="http://howimbuildingmylife.com/wp-content/uploads/2015/08/IMG_8861.jpg" alt="Ms.Whiskas">
      <div class="caption">
        <h3>Ms. Whiskas</h3>
        <p>The Lone Whiska comes out of the Australian Outback...actually that's not true at all. She just wishes that were the case after a couple blokes bet each other that she was actually from Down Under. We can all dream! </p>
      </div>
    </div>
  </div>
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <img src="http://howimbuildingmylife.com/wp-content/uploads/2015/08/FullSizeRender.jpg" alt="Sucker Dood">
      <div class="caption">
        <h3>Sucker Dooder</h3>
        <p>This is Dood. He enjoys sleeps, talking, rubs, and long walks on the beach. He used to hump his sister which was pretty weird, but he's settled down since and keeps it in his fur and reserves it for non-family members.</p>
      </div>
    </div>
  </div>
</div>

app/views/pins/_form.html.erb
<%= form_for(@pin) do |f| %>
      <% if @pin.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

          <ul>
          <% @pin.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= f.label :description %>
        <%= f.text_field :description, class: "form-control" %>
      </div>

   <div class="form-group">   
      <div class="actions">
        <%= f.submit class: "btn btn-primary" %>
      </div>
     </div> 
    <% end %>

app/views/pins/edit.html.erb
		<h1>Editing Pin</h1>

		<%= render 'form' %>

			<%= link_to 'Show', @pin %> |
			<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Pins</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pins.each do |pin| %>
      <tr>
        <td><%= pin.description %></td>
        <td><%= link_to 'Show', pin %></td>
        <td><%= link_to 'Edit', edit_pin_path(pin) %></td>
        <td><%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pin', new_pin_path %>

app/views/pins/new.html.erb
		<h1>New Pin</h1>
	


		<%= render 'form' %>


		<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @pin.description %>
</p>

<%= link_to 'Edit', edit_pin_path(@pin) %> |
<%= link_to 'Back', pins_path %>